<?php
use think\Controller;
use think\Db;

class BaseController extends Controller
{
    protected $beforeActionList = [
      'startTrans'
    ];

    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    protected function startTrans()
    {
        Db::startTrans();
    }

}